### ISSUE TITLE
The deprecated feature ## Colorist

### ISSUE THREAD

**Issue by ShagunThakur47** [mstrimas/colorist#7]
While generating map using map_single(r, pal, lambda_i = -2), a warning message popped up as mentioned below:
**Warning message**:
The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of ggplot2
3.3.4.
ℹ The deprecated feature was likely used in the colorist package.
  Please report the issue at <https://github.com/mstrimas/colorist/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by mstrimas** [comment]
thanks for catching this! the latest CRAN version should have this issue resolved

**Comment by ShagunThakur47** [comment]
Thanks for your response.

Shagun Thakur
